# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dotfiles = {
    pname = "dotfiles";
    version = "2b9da42ed0750457284cb1f9fae57e9bfc910519";
    src = fetchFromGitHub {
      owner = "JonaVDM";
      repo = "dotfiles";
      rev = "2b9da42ed0750457284cb1f9fae57e9bfc910519";
      fetchSubmodules = false;
      sha256 = "sha256-YZnON69Uh4pyxnW99LHnsZZTnyZBwRwHiXhTsFZAqgY=";
    };
    date = "2024-04-11";
  };
  nvim = {
    pname = "nvim";
    version = "8c4962e8eec17abd3139e15c9850345a6d71a5ba";
    src = fetchFromGitHub {
      owner = "JonaVDM";
      repo = "neovim-config";
      rev = "8c4962e8eec17abd3139e15c9850345a6d71a5ba";
      fetchSubmodules = false;
      sha256 = "sha256-IL8CT+z7XSROt86K8dORN7KpH97yyPET1VJIk4YJMCM=";
    };
    date = "2024-04-11";
  };
}
