# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dotfiles = {
    pname = "dotfiles";
    version = "2b9da42ed0750457284cb1f9fae57e9bfc910519";
    src = fetchFromGitHub {
      owner = "JonaVDM";
      repo = "dotfiles";
      rev = "2b9da42ed0750457284cb1f9fae57e9bfc910519";
      fetchSubmodules = false;
      sha256 = "sha256-YZnON69Uh4pyxnW99LHnsZZTnyZBwRwHiXhTsFZAqgY=";
    };
    date = "2024-04-11";
  };
  nvim = {
    pname = "nvim";
    version = "c8755a823cfbcac592cda3cd737172d0e532936d";
    src = fetchFromGitHub {
      owner = "JonaVDM";
      repo = "neovim-config";
      rev = "c8755a823cfbcac592cda3cd737172d0e532936d";
      fetchSubmodules = false;
      sha256 = "sha256-fG1PuCrvu/jpMZ0y5B/B/3gmTPChqhfMPWUN22eGqqE=";
    };
    date = "2024-04-24";
  };
}
