# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dotfiles = {
    pname = "dotfiles";
    version = "2b9da42ed0750457284cb1f9fae57e9bfc910519";
    src = fetchFromGitHub {
      owner = "JonaVDM";
      repo = "dotfiles";
      rev = "2b9da42ed0750457284cb1f9fae57e9bfc910519";
      fetchSubmodules = false;
      sha256 = "sha256-YZnON69Uh4pyxnW99LHnsZZTnyZBwRwHiXhTsFZAqgY=";
    };
    date = "2024-04-11";
  };
  nvim = {
    pname = "nvim";
    version = "c2096416547317cd0f150c1aa21507d878d8d7a8";
    src = fetchFromGitHub {
      owner = "JonaVDM";
      repo = "neovim-config";
      rev = "c2096416547317cd0f150c1aa21507d878d8d7a8";
      fetchSubmodules = false;
      sha256 = "sha256-bAhJYRmmKE1jiGxyDeOA56wznQvO5LGdUfMo5MQB46g=";
    };
    date = "2024-04-14";
  };
}
