name: lint-nix-config
on:
  push:

jobs:
  statix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: run statix lint
        run: nix run nixpkgs#statix -- check . -i **/hardware-configuration.nix _sources flake.nix
